# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'agenda.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nomeAgendaL = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.nomeAgendaL.setFont(font)
        self.nomeAgendaL.setAlignment(QtCore.Qt.AlignCenter)
        self.nomeAgendaL.setObjectName("nomeAgendaL")
        self.horizontalLayout.addWidget(self.nomeAgendaL)
        self.dataAgendaL = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.dataAgendaL.setFont(font)
        self.dataAgendaL.setAlignment(QtCore.Qt.AlignCenter)
        self.dataAgendaL.setObjectName("dataAgendaL")
        self.horizontalLayout.addWidget(self.dataAgendaL)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.nomeClienteC = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.nomeClienteC.setFont(font)
        self.nomeClienteC.setObjectName("nomeClienteC")
        self.gridLayout_2.addWidget(self.nomeClienteC, 0, 0, 1, 1)
        self.clienteB = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.clienteB.setFont(font)
        self.clienteB.setObjectName("clienteB")
        self.gridLayout_2.addWidget(self.clienteB, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Agenda"))
        self.nomeAgendaL.setText(_translate("Dialog", "NOME"))
        self.dataAgendaL.setText(_translate("Dialog", "DATA"))
        self.clienteB.setText(_translate("Dialog", "Ir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
